name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # runs at midnight every day

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install -g svg-term-cli
          npm install

      - name: Generate snake contribution graph
        run: |
          npx svg-term --in=contributions.svg --out=dist/github-contribution-grid-snake.svg --dark=dist/github-contribution-grid-snake-dark.svg --delay=100 --speed=0.1

      - name: Convert SVG to GIF
        run: |
          ffmpeg -i dist/github-contribution-grid-snake.svg -c:v gif -s 1200x600 -preset fast dist/github-contribution-grid-snake.gif

      - name: Upload GIF to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake.gif
          path: dist/github-contribution-grid-snake.gif

      - name: Upload SVGs to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/
